[package]
name = "rust-opengl-glfw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "*"
gl = "*"
cgmath = "*"
lazy_static = "*"
image = "*"
thiserror = "1.0.38"
nalgebra-glm = "0.18.0"
